config/routes.rb
Rails.application.routes.draw do
  resources :films, only: [:index, :new, :create, :destroy]   
   root "resumes#index"  
  get 'films/index'
  get 'films/new'
  get 'films/create'
  get 'films/destroy'  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.   
   validates :title, :category, :year, :price, :attachment, presence: true # Make sure the owner's name is present.   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
    @films = Film.all  
  end

  def new
    @film = Film.new
  end

  def create
    @film = Film.new(film_params)   
      respond_to do |format|
      if @film.save   
      format.html {redirect_to films_path, notice: 'Film was Successfully uploaded.'}   
      format.json {render :show, status: :created, location: @film}
      else   
        format.html {render :new }
        format.json {render json: @film.errors, status: :unprocessable_entity } 
      end   
    end
 end

  def destroy
    @film = Film.find(params[:id])   
    @film.destroy   
    redirect_to films_path, notice:  "Successfully deleted."   
  end
  private   
  def film_params   
  params.require(:film).permit(:title, :category, :year, :price, :attachment)   
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/create.html.erb
<h1>Films#create</h1>
<p>Find me in app/views/films/create.html.erb</p>

app/views/films/destroy.html.erb
<h1>Films#destroy</h1>
<p>Find me in app/views/films/destroy.html.erb</p>

app/views/films/index.html.erb
<style>
h1{
  text-align:center;
  color:green;
}
.card-img-top{
  height:200px;
  weight:250px;
}
.card-body{
   height:200px;
  weight:100px;
}
footer{
  background: black;
}
footer p{
  text-align:center;
  color:white;
}
</style>
<div class="container">   
<% if !flash[:notice].blank? %>   
   <div>   
      <%= flash[:notice] %>   
   </div>   
<% end %>   
  <h1><b>JORAH ENTERTAINMENT SITE<b></h1>
<br>
<br>   
  
<center><b><u><h4><%= link_to "Upload New Movie", new_film_path %></h4></u></b></center>   
<br>   
<br>   
    

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
      <% @films.each do |film| %> 
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
          <img src="<%= film.attachment %>" class="card-img-top" alt="card img cap"> 
      
            <div class="card-body">
              <p class="card-text"><b>Title:</b><%= film.title %><br><b>category:</b><%= film.category %><br><b>Year:</b><%= film.year %><br><b>Price:</b><%= film.price %></p>
             <b><u><%= link_to "Download", film.attachment_url %></u></b>
               <b><u><%= link_to "Delete",  film, method: :delete, confirm: "Are you sure you want to delete #{film.attachment}?" %></u></b>
              </div>
            </div>
          </div>
              <% end %>   
        </div>
    
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>Movie Album is Full &copy; </p>
    <p>JORAH ENTERTAINMENT SITE &copy; 2019</p>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script></body>

app/views/films/new.html.erb
<style>
h1{
  text-align:center;
  color:green;
}
.container{
  margin-left:30%;
   padding-top:30px;
}
.container p{
   padding:-20px; 
}
.container label{
   text-align:center;
   color:green;
   padding:-20px;
}
.container button{
   background:green;
   color:green;
}
.buttons p{
  margin-left:35;
}
</style>
<h1>JORAH ENTERTAINMENT SITE</h1> 
<div class="container">   
   <%= form_for @film, html: { multipart: true } do |f| %>   
      <label><%= f.label :title%> </label>
      <p><%= f.text_field :title %></p>   
      <br><br>  
      <%= f.label :category %>   
      <p><%= f.text_field :category %> </p>
      <br><br>  
      <%= f.label :Release_year %>   
      <p><%= f.text_field :year %> </p> 
      <br><br> 
      <%= f.label :price %>   
     <p> <%= f.text_field :price %> </p>
      <br><br> 
     <%= f.label :attachment %>  
      <%= f.file_field :attachment %>
      <br>   
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>   
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>File Uploading</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'=> true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
  </head>

  <body>
  <div>
    <%= yield %>
    </div>
  </body>
</html>